### ISSUE TITLE
Camunda Function as a Service Endpoints

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Services#42]
Ability to call Functions as a service that active a camunda process.

# Todos:

- [ ] create FaaS Service Type in Service Directory

----

# Design Notes

1. Support POST and GET
1. Body should be transformed into Camunda Variables
1. Camunda `variablesInReturn` property should configure the returned API
   1. Body
   1. Status Code
1. Ability to call a BPMN based on key and based on ID

**Comment by StephenOTT** [comment]
related context: https://forum.camunda.org/t/replacing-http-connector-with-jsoup-usage/5291/3?u=stephenott

**Comment by StephenOTT** [comment]
# Camunda History Time to Live

Note that History Time to list should likely be set to 1 day as it will take up lots of DB data for all of the transactions

# Rate limiting

Also look rate limiting implementations to ensure the API is not abused

**Comment by StephenOTT** [comment]
- [ ] Add Support for GET and query Params

Initial Notes:

1. Every variable is returned as a string? or should be do type sensing?


User Case:

Allow Email approval with a link

**Comment by StephenOTT** [comment]
![confirmation link scenario](https://user-images.githubusercontent.com/1994838/32852962-b58f7454-ca07-11e7-981e-575269d97a39.png)

**Comment by StephenOTT** [comment]
- [ ] add support for anonymous functions (that do not require any header/JWT)

- [ ] Add support for middleware to detect that a user is making a request as a authenticated user and thus pass the JWT/Identity information into the process (similar to a regular process)

**Comment by StephenOTT** [comment]
Function Example:

```
title Camunda Function as a Service

Client->+Proxy: Function Request
Proxy->+Services: Function Request
Services->Services: Process Client Request
Services->Proxy: Camunda Process Activation
Proxy->+Camunda: Camunda Process Activation
Camunda->Camunda: Process Script(s)
Camunda->+Carto.com: GIS/Web Query
Carto.com->-Camunda: GIS Response
Camunda->Camunda: Process GIS Response
Camunda->-Proxy: Camunda Response
Proxy->Services: Camunda Response
Services->Services: Process Camunda Response

Services->-Proxy: Processed Response
Proxy->-Client: Processed Response
```

![function with proxy](https://user-images.githubusercontent.com/1994838/33397047-65845d8c-d518-11e7-9bac-3bd98bbcc4ba.png)
